include(InstallRequiredSystemLibraries)

set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME "strategy")
set(CPACK_PACKAGE_VENDOR "M")
set(CPACK_PACKAGE_CONTACT "m")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Strategy pattern example")

set(CPACK_PACKAGE_VERSION_MAJOR 1)
set(CPACK_PACKAGE_VERSION_MINOR 0)
set(CPACK_PACKAGE_VERSION_PATCH 0)
set(CPACK_PACKAGE_VERSION "1.0.0")

set(CPACK_DEBIAN_PACKAGE_NAME "strategy")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Matvey")

include(CPack)
